---
gitlab_agent_chart_repo_name: "gitlab-io"
gitlab_agent_chart_repo_url: "https://charts.gitlab.io"
gitlab_agent_chart_name: "gitlab-agent"
gitlab_agent_chart_version: "2.27.0"

gitlab_agent_image_repository: "registry.gitlab.com/gitlab-org/cluster-integration/gitlab-agent"
gitlab_agent_image_name: "agentk"
gitlab_agent_image_tag: "v19.0.1@sha256:9b1f074e758263227c25abb6fc86af895ba672cb01fc8663c32c41af5a80af02"
gitlab_agent_image_pull_policy: "IfNotPresent"
gitlab_agent_image_pull_secrets: []

gitlab_agent_replicas: 2

# default values in vars/main.yml
gitlab_agent_instances: []
#  - kas_address: ""
#    token: "" # token or secret_name has to be defined
#    secret_name: ""
#    release_name: ""
#    namespace: ""
#    target_namespace: "" # only used when use_default_roles is true
#    rbac_create: true
#    rbac_role: "cluster-admin" # optional, defaults to ''
#    roles: none # optional, defaults to _gitlab_agent_roles from vars/main.yml
#    rolebindings: none # optional, defaults to _gitlab_agent_rolebindings from vars/main.yml
#    state: "present" # optional, defaults to 'present'
#    service_account_create: true # optional, defaults to true
#    service_account_annotations: {} # optional, defaults to {}
#    service_account_name: "" # optional, defaults to '' (empty -> generated via helm)

gitlab_agent_service_monitor_enabled: true
