---
- name: Create clamav logrotate config
  copy:
    content: |
      /var/log/clamav/*.log {
        rotate 28
        daily
        compress
        missingok
        delaycompress
        copytruncate
        create 640 clamav clamav
        su clamav clamav
      }
    dest: /etc/logrotate.d/clamav
    mode: "0644"
