---
- name: Update Kubernetes roles
  import_tasks: update_roles.yml
  when: update_roles

- name: Update service accounts and tokens
  import_tasks: update_serviceaccounts.yml
  when: update_serviceaccounts

- name: Update role bindings
  import_tasks: update_role_bindings.yml
  when: update_role_bindings
