---
- name: Create service accounts and tokens
  vars:
    serviceaccount_name: "{{ item.0.serviceaccount_name | default(item.0.name, true) }}"
    serviceaccount_namespace: "{{ item.1.namespace | default('default', true) }}"
    generate_new_token: "{{ item.0.name in (regenerate_users | default([])) }}"
  loop: "{{ present_users | subelements('permissions.kubernetes', skip_missing=True) }}"
  loop_control:
    label: "{{ item.0.name }}-{{ item.1.hosts }}-{{ item.1.role }}"
  when: inventory_hostname in (lookup('inventory_hostnames', item.1.hosts) | default('', true)).split(',')
  block:
    - name: Create ServiceAccount {{ serviceaccount_name }} if not present
      kubernetes.core.k8s:
        state: present
        kubeconfig: "{{ kubeconfig }}"
        proxy: "{{ proxy_url | default(omit, true) }}"
        proxy_headers: "{{ proxy_headers | default(omit, true) }}"
        wait: yes
        definition:
          kind: ServiceAccount
          apiVersion: v1
          metadata:
            name: "{{ serviceaccount_name }}"
            namespace: "{{ serviceaccount_namespace }}"
          secrets:
            - name: "{{ serviceaccount_name }}-token"
      register: serviceaccount
      retries: 2
      delay: 10
      tags: serviceaccount

    - name: Create the Secret that entails the token for {{ serviceaccount_name }}
      kubernetes.core.k8s:
        state: present
        force: "{{ generate_new_token }}"
        kubeconfig: "{{ kubeconfig }}"
        proxy: "{{ proxy_url | default(omit, true) }}"
        proxy_headers: "{{ proxy_headers | default(omit, true) }}"
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: "{{ serviceaccount_name }}-token"
            namespace: "{{ serviceaccount_namespace }}"
            annotations:
              kubernetes.io/service-account.name: "{{ serviceaccount_name }}"
          type: kubernetes.io/service-account-token
      register: tokencreation
      retries: 2
      delay: 10
      tags: serviceaccount

    - name: Get tokens for {{ serviceaccount_name }}
      kubernetes.core.k8s:
        state: present
        kubeconfig: "{{ kubeconfig }}"
        proxy: "{{ proxy_url | default(omit, true) }}"
        proxy_headers: "{{ proxy_headers | default(omit, true) }}"
        definition:
          kind: Secret
          apiVersion: v1
          metadata:
            name: "{{ serviceaccount.result.secrets[0].name }}"
            namespace: "{{ serviceaccount_namespace }}"
      register: serviceaccount_token
      retries: 2
      delay: 10
      tags: serviceaccount

    - name: "Check that the values registered in a loop didn't get mixed up ({{ serviceaccount_name }})"
      debug:
        msg: ""
      failed_when: not ansible_check_mode and serviceaccount_token.result.metadata.annotations['kubernetes.io/service-account.name'] != serviceaccount_name
