---
- name: Create the tunnel user
  ansible.builtin.user:
    name: "{{ autossh_tunnel_user }}"
    comment: "the autossh tunnel user"
    create_home: true
    group: "nogroup"
    shell: "/bin/false"
  become: true

- name: create the .ssh directory for the tunner user
  ansible.builtin.file:
    path: "~/.ssh"
    state: directory
    mode: '0700'
  become: true
  become_user: "{{ autossh_tunnel_user }}"

- name: Install the ssh config
  template:
    src: "config"
    dest: "~/.ssh/config"
    mode: '0600'
  become: true
  become_user: "{{ autossh_tunnel_user }}"

- name: Install the systemd unit file
  template:
    src: "autossh@.service"
    dest: "/etc/systemd/system/autossh@{{ item.name }}.service"
  loop: "{{ autossh_tunnel_hosts }}"

- name: Enable and start the systemd service
  ansible.builtin.systemd_service:
    name: "autossh@{{ item.name }}.service"
    enabled: true
    state: started
  loop: "{{ autossh_tunnel_hosts }}"
