---
- name: debug
  ansible.builtin.debug:
    msg:
      - "debug"
      # - "instance {{ instance }}"
      # - "item {{ item }}"
      # - "item.name {{ item.name }}"
      - "item.0.name {{ item.0.name }}"
      # - "item.overlay_name {{ item.1.overlay_name }}"
      - "item.1.overlay_name {{ item.1.overlay_name }}"
      # - "item.overlay_name {{ item.1.bbb_greenlight_custom_locale.overlay_name }}"

- name: Load file content
  ansible.builtin.uri:
    url: "{{ item.1.source }}"
    return_content: true
  register: overlay_file

- set_fact:
    overlay_file: "{{ greenlight_patch_rule }}"

- name: Create volume dir
  ansible.builtin.file:
    path: "/docker_volumes/content_overlay_{{ item.0.name }}_{{ item.1.overlay_name }}"
    state: directory
    mode: '644'
- ansible.builtin.copy:
    content: "{{ overlay_file | to_nice_json }}"
    dest: "/docker_volumes/content_overlay_{{ item.0.name }}_{{ item.1.overlay_name }}/{{ item.1.overlay_name }}"
  notify: Restart scalelite-nginx
  