---
- name: Load file content
  ansible.builtin.uri:
    url: https://raw.githubusercontent.com/bigbluebutton/greenlight/refs/heads/master/app/assets/locales/de.json
    return_content: true
  register: bbb_greenlight_overlay_file

- name: tidy json
  set_fact:
    bbb_greenlight_overlay_file: "{{ ( bbb_greenlight_overlay_file | to_json | from_json).content }}"

- name: apply patch welcome json
  set_fact:
    bbb_greenlight_overlay_file: "{{ bbb_greenlight_overlay_file | combine(item.bbb_greenlight_custom_locale) }}"

- name: Create docker volume
  ansible.builtin.file:
    path: "/docker_volumes/content_overlay_{{ item.name }}_dejson"
    state: directory
    mode: '644'

- name: Save patched json in docker_volume
  ansible.builtin.copy:
    content: "{{ bbb_greenlight_overlay_file }}"
    dest: "/docker_volumes/content_overlay_{{ item.name }}_dejson/de.json"
  notify: Restart scalelite-nginx
