---
- name: "Check if PG_VERSION exists"
  ansible.builtin.stat:
    path: "{{ scalelite_docker_volumes_folder }}/postgres_data/PG_VERSION"
  register: scalelite_postgres_version_file

- name: "Read PG_VERSION"
  ansible.builtin.slurp:
    src: "{{ scalelite_docker_volumes_folder }}/postgres_data/PG_VERSION"
  register: scalelite_postgres_version_file_content
  when:
    - "scalelite_postgres_version_file.stat.exists"

- name: "Set scalelite_postgres_current_datadir_major"
  ansible.builtin.set_fact:
    scalelite_postgres_current_datadir_major: >-
      {% if scalelite_postgres_version_file.stat.exists %}
      {{ scalelite_postgres_version_file_content.content | b64decode | int }}
      {% else %}
      0
      {% endif %}

- name: "Run postgres upgrade if required"
  ansible.builtin.include_tasks: "postgres_upgrade_main.yml"
  when:
    - "scalelite_postgres_needs_upgrade"
