---

- name: restart sshd
  service: 
    name: sshd
    state: restarted
  
- name: restart fail2ban
  service:
    name: fail2ban
    state: restarted
    enabled: yes

- name: Reload ha-cluster-exporter
  ansible.builtin.service:
    name: ha-cluster-exporter
    enabled: true
    state: reloaded

- name: restart uwsgi
  command:
    cmd: /usr/sbin/pcs resource restart uwsgi
  become: true
  when: is_main_node

- name: Restart exporter
  command:
    cmd: /usr/sbin/pcs resource restart custom-exporter
  become: true
  when: is_main_node

# keep for compatibility to non-ha role
- name: reload nginx
  command:
    cmd: /usr/sbin/pcs resource restart nginx
  become: true
  when: is_main_node

- name: restart nginx
  command:
    cmd: /usr/sbin/pcs resource restart nginx
  become: true
  when: is_main_node
