---
- name: Restart Fail2ban
  systemd:
    name: fail2ban
    state: restarted

- name: Restart Coturn
  community.docker.docker_compose_v2:
    project_src: "{{ coturn_docker_compose_folder }}"
    state: restarted
    services: coturn
