---
- name: Add bitnami chart repo
  kubernetes.core.helm_repository:
    name: bitnami
    repo_url: "https://charts.bitnami.com/bitnami"
  check_mode: false
  changed_when: false
  tags: kube-events


