---
scalelite_docker_volumes_folder: /docker_volumes
scalelite_docker_compose_folder: /scalelite
scalelite_docker_compose_owner: root
scalelite_docker_compose_group: root

scalelite_certbot_image_repository: certbot/certbot
scalelite_certbot_image_tag: "v5.4.0@sha256:c23159d30afdd9c97960578aa4654f5901de6cae394958f894074dedd55e599d"
# Custom UID to run certbot as
scalelite_certbot_user_id: 9999
scalelite_certbot_group_id: 9999
# scalelite_certbot_terraform_telekom_os_access_key:
# scalelite_certbot_terraform_telekom_os_secret_key:
# scalelite_certbot_terraform_telekom_domain:
# scalelite_certbot_terraform_telekom_tenant:
# scalelite_certbot_terraform_telekom_dns_zone_id:
# scalelite_certbot_terraform_state_bucket:
# scalelite_certbot_terraform_state_key:
# scalelite_certbot_terraform_state_region:
# scalelite_certbot_terraform_state_endpoint:
scalelite_certbot_terraform_version: 1.5.4
scalelite_certbot_resources:
  reservations:
    cpus: '0.1'
    memory: 50M
  limits:
    cpus: '1'
    memory: 150M
# scalelite_letsencrypt_email:



scalelite_greenlight_enabled: false
scalelite_greenlight_image_repository: greenlight
scalelite_greenlight_image_tag: v3.8.2.3.0@sha256:4602740d9eea29095b876c1ef40e3abee053e9d6bac086db8ba93cf6b2b547a3
scalelite_greenlight_user_id: 999
scalelite_greenlight_extra_instances: []
scalelite_greenlight_default_locale: de
scalelite_greenlight_log_level: warn
scalelite_greenlight_allow_mail_notifications: true
# scalelite_greenlight_smtp_server:
# scalelite_greenlight_smtp_port:
# scalelite_greenlight_smtp_domain:
# scalelite_greenlight_smtp_username:
# scalelite_greenlight_smtp_password:
# scalelite_greenlight_smtp_auth:
# scalelite_greenlight_smtp_sender
# scalelite_bbb_tenant_api_key:
scalelite_greenlight_smtp_auth: plain
scalelite_greenlight_smtp_starttls_auto: true
scalelite_greenlight_phone_number: ""
scalelite_greenlight_resources:
  reservations:
    cpus: '0.1'
    memory: 150M
  limits:
    cpus: "{{ ansible_facts['processor_vcpus'] / 2 }}"
    memory: "{{ ansible_facts['memory_mb']['real']['total'] / 2 }}M"

# Postgres Docker image runs as postgres:postgres (70:70)
scalelite_postgres_user_id: 70
scalelite_postgres_group_id: 70

# this variable is parsed via regex (see vars/main.yml), please keep the scheme (or update the regex if required)
scalelite_postgres_image: "postgres:18.3-alpine@sha256:4da1a4828be12604092fa55311276f08f9224a74a62dcb4708bd7439e2a03911"

# to update the major version:
# copy value of `scalelite_postgres_image` to `scalelite_postgres_image_previous`,
# set scalelite_postgres_image to the new major version
# and do a rollout. The logic detects the currently used version and does an upgrade if needed.
scalelite_postgres_image_previous: "postgres:14.8-alpine@sha256:fa48198f8c88d5563e7ff3f6d5d269be58a7571e4464d70e4cb6c0987d903ba3"

# see above
scalelite_postgres_major_upgrade_allowed: false

scalelite_postgres_resources:
  reservations:
    cpus: '0.2'
    memory: 50M
  limits:
    cpus: "{{ ansible_facts['processor_vcpus'] / 2 }}"
    memory: "{{ ansible_facts['memory_mb']['real']['total'] / 2 }}M"
# prometheuscommunity/postgres-exporter:v0.17.1
scalelite_postgres_exporter_image: prometheuscommunity/postgres-exporter@sha256:38606faa38c54787525fb0ff2fd6b41b4cfb75d455c1df294927c5f611699b17
scalelite_postgres_exporter_resources:
  reservations:
    cpus: '0.1'
    memory: 10M
  limits:
    cpus: "0.5"
    memory: "30M"
# redis:7.2.4-alpine
scalelite_redis_image: redis@sha256:c8bb255c3559b3e458766db810aa7b3c7af1235b204cfdb304e79ff388fe1a5a
# Redis Docker image runs as redis:redis (999:1000)
scalelite_redis_user_id: 999
scalelite_redis_group_id: 1000
scalelite_redis_resources:
  reservations:
    cpus: '0.1'
    memory: 10M
  limits:
    cpus: "{{ ansible_facts['processor_vcpus'] / 2 }}"
    memory: "{{ ansible_facts['memory_mb']['real']['total'] / 2 }}M"

# Connection redis-user
scalelite_redis_user: "worker"
# scalelite_redis_password: "1_SomeSecretPassword_!"  
scalelite_greenlight_redis_user: "greenlight"
# scalelite_greenlight_redis_password: "2_SomeSecretPassword_!"  

scalelite_nginx_image: >-
  {{
    'owasp/modsecurity-crs:4.23.0-nginx-alpine-202602050102'
    if scalelite_modsec_enabled else 
    'nginxinc/nginx-unprivileged:1.24-alpine3.18' 
  }}
scalelite_nginx_user_id: 101
scalelite_nginx_group_id: "{{ scalelite_certbot_group_id }}"
scalelite_nginx_logs_folder: /var/log/nginx
scalelite_nginx_dhparam_size: 4096
scalelite_nginx_worker_processes: auto
scalelite_nginx_resources:
  reservations:
    cpus: '0.1'
    memory: 15M
  limits:
    cpus: "{{ ansible_facts['processor_vcpus'] / 2 }}"
    memory: "{{ ansible_facts['memory_mb']['real']['total'] / 2 }}M"
scalelite_nginx_metrics_endpoints:
  - name: node-exporter
    public_port: 9100
    private_port: 9099
  - name: bbb-autoscaler
    public_port: 9200
    private_port: "{{ scalelite_autoscaler_config.metrics_exporter_port }}"
  - name: cadvisor
    public_port: 9300
    private_port: 9299
  - name: postgres-exporter
    public_port: 9188
    private_port: 9187

scalelite_docker_net: "192.168.64.0/24"
scalelite_modsec_enabled: true
scalelite_modsec_mode: DetectionOnly  # Either DetectionOnly or '"ON"'
# Paranoia level for ModSecurity 
scalelite_modsec_level: 1
# Debug Level for logging
scalelite_modsec_debuglevel: 1 
scalelite_modsec_reportlevel: 1
scalelite_modsec_logs_folder: /var/log/modsec
scalelite_modsec_outbound_anomaly: 4
scalelite_modsec_inbound_anomaly: 5
scalelite_modsec_before: |
  # Dummy comment

scalelite_modsec_after: |
  SecRule REMOTE_ADDR "@ipMatch {{ scalelite_docker_net }}"                     "id:1001, phase:1, pass, nolog,   allow"
  SecRule REQUEST_URI "@beginsWith /fsapi"                                      "id:1002, phase:1, pass, nolog,   ctl:ruleRemoveById=932230"
  SecRule REQUEST_URI "@beginsWith /fsapi"                                      "id:1003, phase:1, pass, nolog,   ctl:ruleRemoveById=932250"
  SecRule REQUEST_URI "@beginsWith /fsapi"                                      "id:1004, phase:1, pass, nolog,   ctl:ruleRemoveById=949110"
  SecRule REQUEST_URI "@contains /greenlight/api/v1/rooms"                      "id:1005, phase:1, pass, nolog,   allow"
  SecRule REQUEST_URI "@contains /greenlight/api/v1/room_settings"              "id:1006, phase:1, pass, nolog,   allow"
  SecRule REQUEST_URI "@contains /greenlight/api/v1/sessions/signout.json"      "id:1007, phase:1, pass, nolog,   allow"
  SecRule REQUEST_URI "@contains /greenlight/api/v1/users"                      "id:1008, phase:1, pass, nolog,   allow"
  SecRule REQUEST_URI "@contains /greenlight/api/v1/admin/site_settings"        "id:1009, phase:1, pass, nolog,   allow"
  SecRule REQUEST_URI "@contains /greenlight/api/v1/admin/rooms_configurations" "id:1010, phase:1, pass, nolog,   allow"
  SecRule REQUEST_URI "@contains /greenlight/api/v1/admin/users"                "id:1011, phase:1, pass, nolog,   allow"
  SecRule REQUEST_URI "@contains /greenlight/api/v1/admin/invitations"          "id:1012, phase:1, pass, nolog,   allow"
  SecRule REQUEST_URI "@contains /greenlight/api/v1/admin/roles"                "id:1013, phase:1, pass, nolog,   allow"
  SecAction "id:980145,phase:5,pass,t:none,log,noauditlog, msg:'Incoming and Outgoing Score: %{TX.ANOMALY_SCORE} %{TX.OUTBOUND_ANOMALY_SCORE}'"
  SecRuleRemoveById 980130

scalelite_user_id: 1000
scalelite_group_id: 1000
scalelite_web_concurrency: 4
scalelite_rails_max_threads: 4
scalelite_log_level: warn
scalelite_multitenancy_enabled: true

scalelite_poller_image: blindsidenetwks/scalelite:v1.8.1-jammy300-alpine-poller@sha256:0b6a94a880fe584c5230c1caf0f582c42f9068da4b9ad3496cfe4cc05d2a7f94
scalelite_api_image: blindsidenetwks/scalelite:v1.8.1-jammy300-alpine-api@sha256:8155cbda34057b84e431bb4595e48624a147a0fed546b1f180191cc50969b741

# scalelite_secret_key_base:
# scalelite_api_key
scalelite_poller_resources:
  reservations:
    cpus: '0.1'
    memory: 100M
  limits:
    cpus: "{{ ansible_facts['processor_vcpus'] / 2 }}"
    memory: "{{ ansible_facts['memory_mb']['real']['total'] / 2 }}M"
scalelite_api_resources:
  reservations:
    cpus: '0.1'
    memory: 250M
  limits:
    cpus: "{{ ansible_facts['processor_vcpus'] / 2 }}"
    memory: "{{ ansible_facts['memory_mb']['real']['total'] / 2 }}M"

scalelite_host: "{{ inventory_hostname }}"
scalelite_redirect_root: false
scalelite_redirect_url: "https://$host/greenlight"
scalelite_basedomain: "{{ inventory_hostname }}"
scalelite_letsencrypt_folder: /etc/letsencrypt
scalelite_terraform_workspace: prod
scalelite_bbb_dialin_enabled: false
scalelite_metrics_basic_auth_username: metrics-user
# scalelite_metrics_basic_auth_password:
scalelite_security_txt: |
  # Security.txt content
scalelite_robots_txt: |
  # Robots.txt content

scalelite_autoscaler_user_id: 65534
scalelite_autoscaler_group_id: 65534
scalelite_autoscaler_image: ghcr.io/dbildungsplattform/infra-autoscaler@sha256:386c018d0c3a8df1a3f03bc5181a6246ea742ee8ae64a589cef131e0d0b3d19c
scalelite_autoscaler_metrics_private_port: 9199
# Autoscaler config as YAML
scalelite_autoscaler_config: {}
# Autoscaler environment variables in name=value format, gets written to the docker-compose file
scalelite_autoscaler_environment: []

scalelite_node_exporter_textfile_directory: /node-exporter-textfiles/
scalelite_node_exporter_user_id: 65534
scalelite_node_exporter_group_id: 65534

scalelite_fail2ban_filter_nginx: |
  [Definition]
  failregex = ^<HOST> - - \[.*\] ".*" (4\d\d|5\d\d) .+$
  ignoreregex =
scalelite_fail2ban_filter_path_nginx: /etc/fail2ban/filter.d/nginx-errors.conf
scalelite_fail2ban_filter_greenlight: |
  [Definition]
  failregex = ^<HOST> - - \[.*\] ".*" (4\d\d|5\d\d) .*\/greenlight\/signin" ".*"$
  ignoreregex =
scalelite_fail2ban_filter_path_greenlight: /etc/fail2ban/filter.d/greenlight-signin-errors.conf
scalelite_fail2ban_jail_nginx: |
  [nginx-http-auth]
  enabled = true
  port = {{ scalelite_nginx_metrics_endpoints | map(attribute='public_port') | join(",") }}
  logpath = {{ scalelite_nginx_logs_folder }}/*.log
  maxretry = 3
  bantime = 3600
  [nginx-errors]
  enabled    = true
  port       = http,https
  filter     = nginx-errors
  logpath    = {{ scalelite_nginx_logs_folder }}/*.log
  maxretry   = 100
  bantime    = 3600
  findtime   = 600
scalelite_fail2ban_jail_path_nginx: /etc/fail2ban/jail.d/nginx_jail.local
scalelite_fail2ban_jail_greenlight: |
  [greenlight-signin-errors]
  enabled    = true
  port       = http,https
  filter     = greenlight-signin-errors
  logpath    = {{ scalelite_nginx_logs_folder }}/*.log
  maxretry   = 5
  bantime    = 3600
scalelite_fail2ban_jail_path_greenlight: /etc/fail2ban/jail.d/greenlight_jail.local

scalelite_clamav_enabled: true
scalelite_clamav_user_id: 2330
scalelite_clamav_group_id: 2330
scalelite_clamav_image_repository: "clamav/clamav"
scalelite_clamav_image_tag: "1.5.2_base@sha256:2218f2b0b8734382ef84e49a9e8d996cd1a0f124fc9c3c8929b421826e05afe9"
scalelite_clamav_log_path: "/var/log/clamav"
scalelite_clamav_db_path: "/var/lib/clamav"
scalelite_clamav_resources:
  limits:
    cpus: '1'
    memory: '1.5G'
  reservations:
    cpus: '0.05'
    memory: '1G'

scalelite_greenlight_extra_instances_login_locale: "https://raw.githubusercontent.com/bigbluebutton/greenlight/refs/tags/{{ scalelite_greenlight_image_tag | regex_replace('^v', 'release-') | regex_replace('@sha256:\\w+$', '') | regex_replace('\\.\\d+$', '') }}/app/assets/locales/de.json"

# bbb_instances_dbp:
#   dp:
#     name: bbb
#     domain_name: 
#     scalelite_host: 
#     ebbba_exporters: true
#     greenlight_extra_instances:
#       - name: name_of_greenlight_extra_instances with separate greenlight and user management
#         custom_locale:
#         # optional content overwrite for greenlight login page
#         # path to origin json set in scalelite_greenlight_extra_instances_login_locale
#         # as for elemnets like "welcome_bbb", "bigbluebutton_description" "greenlight_description"
#           homepage:
#             welcome_bbb: "optional, content for greenlight login page"
#         custom_mounts:
#         # overlay files in greenlight extra instance 
#          - content: |
#             my file contents
#            hostpath: /var/test  # docker volumes path in scalelight server
#            mountpath: /var/test # overlay file path in greenlight extra instances container
