---
postgres_config_custom_command: ""                    # Custom DB command executed after configuration of db and users in the new db
postgres_config_user: postgres                           # Initial/Admin user
psql_auth_db: postgres
postgres_config_name: "{{ postgres_config_db_name | regex_replace('_', '-') }}"               # Used for naming ConfigMap, Secret and Job for better identification
postgres_config_default_privileges: "ALL PRIVILEGES"     # Privilieges used if not provided for a user
postgres_config_db_owner: "{{ postgres_config_db_users[0].name }}"  # Owner of the created DB (name of user)
postgres_config_private_db: false                        # If true: All priviliges for the db are revoked for the public role
# Addionital necessary variables for this role:
# postgres_config_namespace: Namespace for ConfigMap, Secret and Job
# postgres_config_host: Host of DB
# postgres_config_pass: Password for Initial/Admin user (OR postgres_config_pass_key and existing_secret as listed below)
# postgres_config_db_name: Name of the DB
postgres_config_db_users: []                             # List of users to create
#   - name: Name of User
#     password: Password of User
#     privileges: Privileges for user (e.g. "CONNECT" or "ALL PRIVILEGES")
#     allow_db_creation: Give the user rights to create new databases (optional, defaults to false)

# optional: use of an existing secret - currently supports postgres_config_name AND/OR postgres_config_pass
# existing_secret: Secret name
# postgres_config_pass_key: Key of the postgres_config_pass in the existing secret
# postgres_config_name_key: Key of the postgres_config_name in the existing secret
