---
bbb_datacenter_ionos_sd_configs: |
  {% for id in bbb_datacenter_ids %}
  - datacenter_id: "{{ id }}"
    basic_auth:
      {{ bbb_ionos_basic_auth | to_nice_yaml | indent(4) }}
    port: {{ 443 if bbb_ebbba_exporters else 9688 }}
    refresh_interval: 15s
  {% endfor %}
bbb_turn_coturn_datacenter_ionos_sd_configs: |
  {% for id in bbb_datacenter_ids %}
  - datacenter_id: "{{ id }}"
    basic_auth:
      {{ bbb_ionos_basic_auth | to_nice_yaml | indent(4) }}
    port: 9642
    refresh_interval: 15s
  {% endfor %}
bbb_turn_node_datacenter_ionos_sd_configs: |
  {% for id in bbb_datacenter_ids %}
  - datacenter_id: "{{ id }}"
    basic_auth:
      {{ bbb_ionos_basic_auth | to_nice_yaml | indent(4) }}
    port: 9100
    refresh_interval: 15s
  {% endfor %}
bbb_turn_node_datacenter_ionos_sd_configs_cadvisor: |
  {% for id in bbb_datacenter_ids %}
  - datacenter_id: "{{ id }}"
    basic_auth:
      {{ bbb_ionos_basic_auth | to_nice_yaml | indent(4) }}
    port: 9300
    refresh_interval: 15s
  {% endfor %}

bbb_ionos_basic_auth_secret_mount_path: "/etc/bbb/{{ bbb_instance_name }}-ionos"
bbb_ionos_basic_auth:
  username: "{{ bbb_prometheus_ionos_username }}"
  password_file: "{{ bbb_ionos_basic_auth_secret_mount_path }}/{{ bbb_ionos_basic_auth_secret_key }}"
