---
# Gets the admin kubeconfigs from IONOS, only used by AWX
# In all other cases personalized kubeconfigs should already exist in ~/.kube
- name: Ansible Kubernetes role
  throttle: 1
  vars:
    proxy_user: "{{ generate_kubeconfigs_proxy_user_awx }}"
    proxy_pass: "{{ generate_kubeconfigs_proxy_pass_awx }}"
  ansible.builtin.import_role:
    name: dbildungscloud.infra.get_ionos_kubeconfig
  when: awx_job_id is defined
  # This must run even in check mode on AWX
  check_mode: "{{ false if awx_job_id is defined else ansible_check_mode }}"

- name: Create user Kubeconfig folders
  # noqa: run-once[task]
  run_once: true
  ansible.builtin.file:
    path: "/tmp/{{ item.name }}"
    state: directory
    mode: "0700"
  loop: "{{ generate_kubeconfigs_present_users }}"
  loop_control:
    label: "{{ item.name }}"

- name: Get all ServiceAccounts and (Cluster)RoleBindings
  kubernetes.core.k8s_info:
    kind: "{{ item }}"
    kubeconfig: "{{ generate_kubeconfigs_kubeconfig }}"
    proxy: "{{ generate_kubeconfigs_proxy_url | default(omit, true) }}"
    proxy_headers: "{{ generate_kubeconfigs_proxy_headers | default(omit, true) }}"
  register: _r_user_resources
  loop:
    - ServiceAccount
    - RoleBinding
    - ClusterRoleBinding

- name: Remove them for absent_users
  vars:
    _merged_resources: "{{ _r_user_resources.results | map(attribute='resources') | flatten }}"
  kubernetes.core.k8s:
    state: absent
    kubeconfig: "{{ generate_kubeconfigs_kubeconfig }}"
    proxy: "{{ generate_kubeconfigs_proxy_url | default(omit, true) }}"
    proxy_headers: "{{ generate_kubeconfigs_proxy_headers | default(omit, true) }}"
    definition: "{{ item }}"
  loop: "{{ _merged_resources | selectattr('metadata.name', 'in', (generate_kubeconfigs_absent_users | map(attribute='name'))) }}"
  loop_control:
    label: "{{ item.kind }} {{ item.metadata.name }} ({{ item.metadata.namespace | default('') }})"

- name: Remove kubeconfigs of absent_users from 1Password
  # noqa: run-once[task]
  run_once: true
  vars:
    suffixes:
      - "-kubeconfigs"
      - "-kubeconfigs.sha256"
      - "-kubeconfigs.pass"
  dbildungscloud.onepwd.item:
    state: absent
    credentials: "{{ op_credentials }}"
    vault: "{{ generate_kubeconfigs_kubeconfigs_vault }}"
    name: "{{ item }}"
    session_shorthand: ansible-run
  loop: "{{ generate_kubeconfigs_absent_users | map(attribute='name') | product(suffixes) | map('join') | list }}"

- name: Create Kubernetes Cluster Roles
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ generate_kubeconfigs_kubeconfig }}"
    proxy: "{{ generate_kubeconfigs_proxy_url | default(omit, true) }}"
    proxy_headers: "{{ generate_kubeconfigs_proxy_headers | default(omit, true) }}"
    definition:
      kind: ClusterRole
      apiVersion: rbac.authorization.k8s.io/v1
      metadata:
        name: "{{ item.name }}"
        labels: "{{ item.labels | default(omit) }}"
      rules: "{{ item.rules }}"
  loop: "{{ kubernetes_roles }}"
  loop_control:
    label: "{{ item.name }}"
  when: inventory_hostname in (lookup('inventory_hostnames', item.hosts) | default('', true)).split(',')

- name: Create service accounts and generate kubeconfigs
  any_errors_fatal: true
  block:
    - name: Create service accounts and generate kubeconfigs
      vars:
        _create_clusterrole: false
        _clusterrole_name: "{{ item.1.role }}"
        _serviceaccount_name: "{{ item.0.serviceaccount_name | default(item.0.name, true) }}"
        _serviceaccount_role_binding: "{{ 'RoleBinding' if item.1.namespace is defined else 'ClusterRoleBinding' }}"
        _serviceaccount_namespace: "{{ item.1.namespace | default('default', true) }}"
        _proxy_user: "{{ item.0.name }}"
        _generate_new_token: "{{ item.0.name in generate_kubeconfigs_regenerate_users }}"
        _kubeconfig_destination: /tmp/{{ item.0.name }}/{{ generate_kubeconfigs_cluster_name }}.yaml
      ansible.builtin.include_tasks: "serviceaccounts.yml"
      when: inventory_hostname in (lookup('inventory_hostnames', item.1.hosts) | default('', true)).split(',')
      loop: "{{ generate_kubeconfigs_present_users | subelements('permissions.kubernetes', skip_missing=True) }}"
      loop_control:
        label: "{{ item.0.name }}-{{ item.1.hosts }}-{{ item.1.role }}"
    - name: Upload Kubeconfig
      # noqa: run-once[task]
      run_once: true
      vars:
        _user: "{{ item.name }}"
        _personal: "{{ item.personal }}"
      ansible.builtin.include_tasks: "upload-kubeconfig.yml"
      loop: "{{ generate_kubeconfigs_present_users }}"
  always:
    - name: Cleanup temporary files
      # noqa: run-once[task]
      run_once: true
      ansible.builtin.file:
        path: "/tmp/{{ item.name }}"
        state: absent
      loop: "{{ generate_kubeconfigs_present_users }}"
