---
- name: "Create ClusterRole {{ _clusterrole_name }}"
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ generate_kubeconfigs_kubeconfig }}"
    proxy: "{{ generate_kubeconfigs_proxy_url | default(omit, true) }}"
    proxy_headers: "{{ generate_kubeconfigs_proxy_headers | default(omit, true) }}"
    definition:
      kind: ClusterRole
      apiVersion: rbac.authorization.k8s.io/v1
      metadata:
        name: "{{ _clusterrole_name }}"
      rules: "{{ serviceaccount_rules }}"
  when: _create_clusterrole | default(true)
  tags: serviceaccount

- name: "Check if ClusterRoleBinding changed for {{ _serviceaccount_name }}"
  check_mode: true
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ generate_kubeconfigs_kubeconfig }}"
    proxy: "{{ generate_kubeconfigs_proxy_url | default(omit, true) }}"
    proxy_headers: "{{ generate_kubeconfigs_proxy_headers | default(omit, true) }}"
    definition:
      kind: "{{ _serviceaccount_role_binding }}"
      apiVersion: rbac.authorization.k8s.io/v1
      metadata:
        name: "{{ _serviceaccount_name }}"
      subjects:
        - kind: ServiceAccount
          name: "{{ _serviceaccount_name }}"
          namespace: "{{ _serviceaccount_namespace }}"
      roleRef:
        kind: ClusterRole
        name: "{{ _clusterrole_name }}"
        apiGroup: rbac.authorization.k8s.io
  register: clusterrolebinding_check
  when: _serviceaccount_role_binding == "ClusterRoleBinding"
  ignore_errors: true
  tags: serviceaccount

- name: "Delete ClusterRoleBinding to create new one for {{ _serviceaccount_name }}"
  kubernetes.core.k8s:
    state: absent
    kubeconfig: "{{ generate_kubeconfigs_kubeconfig }}"
    proxy: "{{ generate_kubeconfigs_proxy_url | default(omit, true) }}"
    proxy_headers: "{{ generate_kubeconfigs_proxy_headers | default(omit, true) }}"
    definition:
      kind: "{{ _serviceaccount_role_binding }}"
      apiVersion: rbac.authorization.k8s.io/v1
      metadata:
        name: "{{ _serviceaccount_name }}"
  register: clusterrolebinding_change
  when: _serviceaccount_role_binding == "ClusterRoleBinding" and (clusterrolebinding_check is changed or clusterrolebinding_check is failed)
  tags: serviceaccount

- name: "Create ClusterRoleBinding for {{ _serviceaccount_name }}"
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ generate_kubeconfigs_kubeconfig }}"
    proxy: "{{ generate_kubeconfigs_proxy_url | default(omit, true) }}"
    proxy_headers: "{{ generate_kubeconfigs_proxy_headers | default(omit, true) }}"
    definition:
      kind: "{{ _serviceaccount_role_binding }}"
      apiVersion: rbac.authorization.k8s.io/v1
      metadata:
        name: "{{ _serviceaccount_name }}"
      subjects:
        - kind: ServiceAccount
          name: "{{ _serviceaccount_name }}"
          namespace: "{{ _serviceaccount_namespace }}"
      roleRef:
        kind: ClusterRole
        name: "{{ _clusterrole_name }}"
        apiGroup: rbac.authorization.k8s.io
  when: _serviceaccount_role_binding == "ClusterRoleBinding" and (clusterrolebinding_check is changed or clusterrolebinding_check is failed)
  tags: serviceaccount

- name: "Check if RoleBinding changed for {{ _serviceaccount_name }}"
  check_mode: true
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ generate_kubeconfigs_kubeconfig }}"
    proxy: "{{ generate_kubeconfigs_proxy_url | default(omit, true) }}"
    proxy_headers: "{{ generate_kubeconfigs_proxy_headers | default(omit, true) }}"
    definition:
      kind: "{{ _serviceaccount_role_binding }}"
      apiVersion: rbac.authorization.k8s.io/v1
      metadata:
        name: "{{ _serviceaccount_name }}"
        namespace: "{{ _serviceaccount_namespace }}"
      subjects:
        - kind: ServiceAccount
          name: "{{ _serviceaccount_name }}"
          namespace: "{{ _serviceaccount_namespace }}"
      roleRef:
        kind: ClusterRole
        name: "{{ _clusterrole_name }}"
        apiGroup: rbac.authorization.k8s.io
  register: rolebinding_check
  when: _serviceaccount_role_binding == "RoleBinding"
  ignore_errors: true
  tags: serviceaccount

- name: "Delete RoleBinding to create new one for {{ _serviceaccount_name }}"
  kubernetes.core.k8s:
    state: absent
    kubeconfig: "{{ generate_kubeconfigs_kubeconfig }}"
    proxy: "{{ generate_kubeconfigs_proxy_url | default(omit, true) }}"
    proxy_headers: "{{ generate_kubeconfigs_proxy_headers | default(omit, true) }}"
    definition:
      kind: "{{ _serviceaccount_role_binding }}"
      apiVersion: rbac.authorization.k8s.io/v1
      metadata:
        name: "{{ _serviceaccount_name }}"
        namespace: "{{ _serviceaccount_namespace }}"
  when: _serviceaccount_role_binding == "RoleBinding" and (rolebinding_check is changed or rolebinding_check is failed)
  tags: serviceaccount

- name: "Create RoleBinding for {{ _serviceaccount_name }}"
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ generate_kubeconfigs_kubeconfig }}"
    proxy: "{{ generate_kubeconfigs_proxy_url | default(omit, true) }}"
    proxy_headers: "{{ generate_kubeconfigs_proxy_headers | default(omit, true) }}"
    definition:
      kind: "{{ _serviceaccount_role_binding }}"
      apiVersion: rbac.authorization.k8s.io/v1
      metadata:
        name: "{{ _serviceaccount_name }}"
        namespace: "{{ _serviceaccount_namespace }}"
      subjects:
        - kind: ServiceAccount
          name: "{{ _serviceaccount_name }}"
          namespace: "{{ _serviceaccount_namespace }}"
      roleRef:
        kind: ClusterRole
        name: "{{ _clusterrole_name }}"
        apiGroup: rbac.authorization.k8s.io
  when: _serviceaccount_role_binding == "RoleBinding" and (rolebinding_check is changed or rolebinding_check is failed)
  tags: serviceaccount

- name: "Create ServiceAccount if not present: {{ _serviceaccount_name }}"
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ generate_kubeconfigs_kubeconfig }}"
    proxy: "{{ generate_kubeconfigs_proxy_url | default(omit, true) }}"
    proxy_headers: "{{ generate_kubeconfigs_proxy_headers | default(omit, true) }}"
    wait: true
    definition:
      kind: ServiceAccount
      apiVersion: v1
      metadata:
        name: "{{ _serviceaccount_name }}"
        namespace: "{{ _serviceaccount_namespace }}"
      secrets:
        - name: "{{ _serviceaccount_name }}-token"
  register: serviceaccount
  tags: serviceaccount

- name: "Create the Secret that entails the token for {{ _serviceaccount_name }}"
  kubernetes.core.k8s:
    state: present
    force: "{{ generate_new_token | default(false) }}"
    kubeconfig: "{{ generate_kubeconfigs_kubeconfig }}"
    proxy: "{{ generate_kubeconfigs_proxy_url | default(omit, true) }}"
    proxy_headers: "{{ generate_kubeconfigs_proxy_headers | default(omit, true) }}"
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ _serviceaccount_name }}-token"
        namespace: "{{ _serviceaccount_namespace }}"
        annotations:
          kubernetes.io/service-account.name: "{{ _serviceaccount_name }}"
      type: kubernetes.io/service-account-token
  register: tokencreation
  tags: serviceaccount

- name: "Get tokens for {{ _serviceaccount_name }}"
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ generate_kubeconfigs_kubeconfig }}"
    proxy: "{{ generate_kubeconfigs_proxy_url | default(omit, true) }}"
    proxy_headers: "{{ generate_kubeconfigs_proxy_headers | default(omit, true) }}"
    definition:
      kind: Secret
      apiVersion: v1
      metadata:
        name: "{{ serviceaccount.result.secrets[0].name }}"
        namespace: "{{ _serviceaccount_namespace }}"
  register: serviceaccount_token
  tags: serviceaccount

- name: "Check that the values registered in a loop didn't get mixed up ({{ _serviceaccount_name }})"
  ansible.builtin.debug:
    msg: ""
  failed_when: serviceaccount_token.result.metadata.annotations['kubernetes.io/service-account.name'] != _serviceaccount_name11

- name: "Generate kubeconfigs for {{ _serviceaccount_name }}"
  throttle: 1
  vars:
    kubeconfig_yaml: "{{ lookup('file', kubeconfig) | from_yaml }}"
    # Add certificate for the cluster and the ISRG Root X1 certificate (used by Let's Encrypt) for the proxy
    # Source of the ISRG Root X1 certificate: https://letsencrypt.org/de/certificates/
    cluster_cacert: "{{ serviceaccount_token.result.data['ca.crt'] | b64decode }}"
    proxy_cacert: "{{ lookup('file', 'isrgrootx1.pem') }}"
    cacerts: "{{ cluster_cacert }}\n{{ proxy_cacert }}"
    # Load proxy password if a proxy is defined
    proxy_pass: |-
      {{ lookup('dbildungscloud.onepwd.onepwd',
            secret_name=_proxy_user,
            vault=proxy_vault,
            session_shorthand='ansible-run',
            credentials=op_credentials)
        if proxy_domain else '' }}
  ansible.builtin.template:
    src: kubeconfig.yml.j2
    dest: "{{ kubeconfig_destination }}"
    mode: "0600"
  # Ensure that the values registered in a loop didn't get mixed up
  when: kubeconfig_destination is defined
  tags: serviceaccount
