---
- name: Check if there are kubeconfigs to upload
  ansible.builtin.find:
    paths: "/tmp/{{ user }}"
    patterns: "*.yaml"
  register: kubeconfig_files

- name: "No kubeconfigs to upload for {{ user }}"
  ansible.builtin.debug:
    msg: "The folder doesn't contain any kubeconfigs"
  when: kubeconfig_files.matched == 0

- name: "Create archive and check if hash changed for {{ user }}"
  when: kubeconfig_files.matched > 0
  block:
    # The archive contains the access and modification times so this is needed to make it produce consistent hashes
    - name: Set access and modification times for Kubeconfigs
      ansible.builtin.file:
        path: "/tmp/{{ user }}"
        access_time: 202301010000.00
        modification_time: 202301010000.00
        recurse: true

    - name: Archive Kubeconfigs
      community.general.archive:
        path: "/tmp/{{ user }}/*"
        dest: "/tmp/{{ user }}.zip"
        format: zip
        mode: "0600"

    - name: Compute Kubeconfig archive hash
      ansible.builtin.stat:
        path: "/tmp/{{ user }}.zip"
        checksum_algorithm: sha256
      register: stat
      when: personal

    - name: Upload hash to 1Password
      dbildungscloud.onepwd.item:
        vault: "{{ kubeconfigs_vault }}"
        credentials: "{{ op_credentials }}"
        name: "{{ user }}-kubeconfigs.sha256"
        category: Secure Note
        fields:
          - name: notesPlain
            type: text
            value: "{{ stat.stat.checksum }}"
        session_shorthand: ansible-run
      register: upload_hash
      when: personal

- name: "Perform encrypted upload for {{ user }}"
  when: kubeconfig_files.matched > 0 and personal and upload_hash.changed
  block:
    - name: Convert SSH public key to pem format
      ansible.builtin.command:
        cmd: "ssh-keygen -f {{ playbook_dir }}/files/sshkeys/{{ user }}.pub -e -m PKCS8"
      register: pem_key
      changed_when: false

    - name: Create pem public key file
      ansible.builtin.copy:
        content: "{{ pem_key.stdout }}"
        dest: "/tmp/{{ user }}.pem"
        mode: "0600"
      changed_when: false

    - name: Generate AES password
      changed_when: false
      ansible.builtin.command:
        cmd: "openssl rand -base64 -out /tmp/{{ user }}.pass 128"

    - name: Encrypt AES password
      changed_when: false
      ansible.builtin.command:
        cmd: "openssl pkeyutl -encrypt -pubin -inkey /tmp/{{ user }}.pem -in /tmp/{{ user }}.pass -out /tmp/{{ user }}.pass.enc"

    - name: Encrypt Kubeconfig archive
      changed_when: false
      ansible.builtin.command:
        cmd: "openssl enc -aes-256-cbc -pbkdf2 -kfile /tmp/{{ user }}.pass -in /tmp/{{ user }}.zip -out /tmp/{{ user }}.zip.enc"

    - name: Upload encrypted AES password to 1Password
      dbildungscloud.onepwd.document:
        vault: "{{ kubeconfigs_vault }}"
        credentials: "{{ op_credentials }}"
        name: "{{ user }}-kubeconfigs.pass"
        path: "/tmp/{{ user }}.pass.enc"
        session_shorthand: ansible-run

    - name: Upload encrypted Kubeconfig archive to 1Password
      dbildungscloud.onepwd.document:
        vault: "{{ kubeconfigs_vault }}"
        credentials: "{{ op_credentials }}"
        name: "{{ user }}-kubeconfigs"
        path: "/tmp/{{ user }}.zip.enc"
        session_shorthand: ansible-run

- name: "Perform unencrypted upload for {{ user }}"
  when: kubeconfig_files.matched > 0 and not personal
  dbildungscloud.onepwd.document:
    vault: "{{ infra_vault }}"
    credentials: "{{ op_credentials }}"
    name: "{{ user }}-kubeconfigs"
    path: "/tmp/{{ user }}.zip"
    session_shorthand: ansible-run
