_gitlab_agent_instance_defaults:
  rbac_create: false
  rbac_role: ""
  state: "present"
  service_account_create: true
  service_account_annotations: {}
  service_account_name: ""
  roles: null
  rolebindings: null
  target_namespace: ""

_gitlab_agent_instances_with_defaults: |-
  {%- set output = [] %}
  {%- for gli in gitlab_agent_instances %}
    {%- set item = _gitlab_agent_instance_defaults | combine(gli, recursive=True) %}
    {%- set _ = output.append(item) %}
  {%- endfor %}
  {{ output }}
