---
- name: Add aqua security helm chart repo
  kubernetes.core.helm_repository:
    name: aqua
    repo_url: "https://aquasecurity.github.io/helm-charts/"
  when: not trivy_operator_use_oci_repo
  check_mode: false
  changed_when: false
  tags: trivy

- name: Create security namespace for Trivy Operator
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ kubeconfig }}"
    proxy: "{{ proxy_url | default(omit, true) }}"
    proxy_headers: "{{ proxy_headers | default(omit, true) }}"
    api_version: v1
    name: "{{ trivy_operator_release_namespace }}"
    kind: Namespace
  tags: trivy

- name: Install Trivy Operator
  kubernetes.core.helm:
    name: "{{ trivy_operator_release_name }}"
    chart_ref: "{{ trivy_operator_chart_ref }}"
    chart_version: "{{ trivy_operator_helm_chart_version }}"
    update_repo_cache: "{{ trivy_operator_update_repo_cache }}"
    kubeconfig: "{{ kubeconfig }}"
    release_namespace: "{{ trivy_operator_release_namespace }}"
    wait: true
    values: "{{ trivy_values }}"
  tags: trivy
