---
- name: Add Victoriametrics chart repo
  kubernetes.core.helm_repository:
    name: vm
    repo_url: "https://victoriametrics.github.io/helm-charts/"
  check_mode: false
  changed_when: false
  tags:
  - victoriametrics-l
  - vmagent

- import_tasks: vm_l.yml
- import_tasks: vm_agent.yml
