---
- name: Add kyverno chart repo
  kubernetes.core.helm_repository:
    name: kyverno
    repo_url: https://kyverno.github.io/kyverno/
  check_mode: false
  changed_when: false

- name: Install kyverno
  kubernetes.core.helm:
    name: kyverno
    create_namespace: yes
    chart_ref: kyverno/kyverno
    wait: yes
    chart_version: "{{ kyverno_chart_version }}"
    kubeconfig: "{{ kubeconfig }}"
    release_namespace: "{{ kyverno_namespace }}"
    values: "{{ kyverno_values }}"
