---
- name: Restart Fail2ban
  systemd:
    name: fail2ban
    state: restarted

- name: Restart Scalelite
  community.docker.docker_compose_v2:
    project_src: "{{ scalelite_docker_compose_folder }}"
    state: restarted
    services: scalelite-api

- name: Restart scalelite-nginx
  community.docker.docker_compose_v2:
    project_src: "{{ scalelite_docker_compose_folder }}"
    state: restarted
    services: scalelite-nginx

- name: Restart bbb-autoscaler
  community.docker.docker_compose_v2:
    project_src: "{{ scalelite_docker_compose_folder }}"
    state: restarted
    services: bbb-autoscaler

- name: Restart postgres
  community.docker.docker_compose_v2:
    project_src: "{{ scalelite_docker_compose_folder }}"
    state: restarted
    services: db

- name: Restart Redis redis_data
  community.docker.docker_compose_v2:
    project_src: "{{ scalelite_docker_compose_folder }}"
    state: restarted
    services: redis

- name: Restart Redis redis_greenlight_data
  community.docker.docker_compose_v2:
    project_src: "{{ scalelite_docker_compose_folder }}"
    state: restarted
    services: redis-greenlight

- name: Restart Redis Instaces
  community.docker.docker_compose_v2:
    project_src: "{{ scalelite_docker_compose_folder }}"
    state: restarted
    services: redis-{{ item.name }}
  loop: "{{ scalelite_greenlight_extra_instances }}"
  loop_control:
    label: "{{ item.name }}"
